export const FIELD_UPDATE_VALUE = 'FIELD_UPDATE_VALUE';
export const FIELD_VALIDATE_SUCCESS = 'FIELD_VALIDATE_SUCCESS';
export const FIELD_VALIDATE_FAILURE = 'FIELD_VALIDATE_FAILURE';
export const FORM_INIT = 'FORM_INIT';
export const FORM_RESET = 'FORM_RESET';
